### ISSUE TITLE
I am asking question here because i was not able to open in fork.

### ISSUE THREAD

**Issue by Enigma10** [peacepostman/eve-quick-market#1]
Hi,

Sorry for the opening issue here. But can you help me to run vime player ?. I  ran the following commands:

```
run npm install
cd core and run npm install
npm run serve
```
and I tried to run playground.html. But it is giving me this error. 

```
consoleError @ index-1c1d24da.js:2695
index-1c1d24da.js:1939 Uncaught (in promise) Error: Constructor for "vm-player#undefined" was not found
    at initializeComponent (index-1c1d24da.js:1939)
index-1c1d24da.js:2695 SyntaxError: Unexpected token '.' undefined
consoleError @ index-1c1d24da.js:2695
index-1c1d24da.js:1939 Uncaught (in promise) Error: Constructor for "vm-default-ui#undefined" was not found
    at initializeComponent 
```

the creator is less active on this project due to a new project and I think my issue is s dumb. But it will big help if you can help to run this project. I am trying to fix two issue
1. Fullscreen 
2. CSS is loading

**Comment by peacepostman** [comment]
Hello,

It is, indeed, a surprising place to leave an issue :D

I simply follow this readme to fork and run the vimejs project: https://github.com/vime-js/vime/blob/master/.github/CONTRIBUTING.md.

Personnally, i only ran `npm install` in the `core` folder, not on the root of the project. If this error still persist, maybe have a look on your node version.

Best regards

Edit: i've noticed that you wrote `run npm install`, maybe it is a typo but i just ran `npm install`

**Comment by Enigma10** [comment]
@peacepostman again, no success. it just that whenever I am trying to access `playground.html` after running the project. I am getting these errors in the console. 
```
consoleError @ index-1c1d24da.js:2695
index-1c1d24da.js:1939 Uncaught (in promise) Error: Constructor for "vm-player#undefined" was not found
    at initializeComponent (index-1c1d24da.js:1939)
index-1c1d24da.js:2695 SyntaxError: Unexpected token '.' undefined
consoleError @ index-1c1d24da.js:2695
index-1c1d24da.js:1939 Uncaught (in promise) Error: Constructor for "vm-default-ui#undefined" was not found
    at initializeComponent
```
how did you able to see the player?  I am not able
